export const data = [
  {
    memberID: 1,
    avatar: "VINET",
    name: "Le Ngoc Minh",
    birthdate: "27-04-2002",
    gender: "Male",
    relationship: "Farther",
    phone: "0377610695",
    email: "minh123nzd@gmail.com",
    address: "KTX Khu A, DHQG",
  },
  {
    memberID: 2,
    avatar: "VINET",
    name: "Tran Van Anh",
    birthdate: "22-09-1995",
    gender: "Male",
    relationship: "Brother",
    phone: "0988777666",
    email: "anhtran@gmail.com",
    address: "12 Hoang Diem, Hanoi",
  },
  {
    memberID: 3,
    avatar: "VINET",
    name: "Nguyen Thi Mai",
    birthdate: "01-02-1987",
    gender: "Female",
    relationship: "Mother",
    phone: "0909123456",
    email: "mainguyen@gmail.com",
    address: "14 Le Dai Hanh, HCMC",
  },
  {
    memberID: 4,
    avatar: "VINET",
    name: "Pham Van Thong",
    birthdate: "08-05-1999",
    gender: "Male",
    relationship: "Friend",
    phone: "0977123123",
    email: "thongpv@gmail.com",
    address: "43 Tran Nhan Tong, Hue",
  },
  {
    memberID: 5,
    avatar: "VINET",
    name: "Doan Thi Hien",
    birthdate: "16-12-1994",
    gender: "Female",
    relationship: "Sister",
    phone: "0966123123",
    email: "hien.doan@gmail.com",
    address: "27 Nguyen Trai, Hanoi",
  },
  {
    memberID: 6,
    avatar: "VINET",
    name: "Phan Anh Tuan",
    birthdate: "05-03-1998",
    gender: "Male",
    relationship: "Friend",
    phone: "0948123456",
    email: "tuanphananh@gmail.com",
    address: "24 Tran Quang Dieu, HCMC",
  },
  {
    memberID: 7,
    avatar: "VINET",
    name: "Vu Thi Thu",
    birthdate: "29-11-1992",
    gender: "Female",
    relationship: "Friend",
    phone: "0912123456",
    email: "thuvu92@gmail.com",
    address: "28 Nguyen Van Cu, Hanoi",
  },
  {
    memberID: 8,
    avatar: "VINET",
    name: "Bui Van Khoi",
    birthdate: "20-07-2000",
    gender: "Male",
    relationship: "Friend",
    phone: "0987123456",
    email: "khoibv@gmail.com",
    address: "15 Le Lai, Hue",
  },
  {
    memberID: 9,
    avatar: "VINET",
    name: "Tran Thi Hong",
    birthdate: "21-01-1985",
    gender: "Female",
    relationship: "Aunt",
    phone: "0978123456",
    email: "hongtran85@gmail.com",
    address: "18 Nguyen Du, HCMC",
  },
  {
    memberID: 10,
    avatar: "VINET",
    name: "Nguyen Van Huy",
    birthdate: "11-10-1997",
    gender: "Male",
    relationship: "Friend",
    phone: "0963123456",
    email: "huy.nguyenvan@gmail.com",
    address: "23 Tran Quoc Toan, Hanoi",
  },
];
